#!/usr/bin/python
# -*- coding: utf-8 -*-

_xml_satisfaction_tag = "Satisfaction"
_xml_dissatisfaction_tag = "Dissatisfaction"
_xml_disagreement_tag = "Disagreement"
_xml_agreement_tag = "Agreement"
_xml_pleasure_tag = "Pleasure"

_words = {
    "ne me satisfaisait plus entièrement": [_xml_dissatisfaction_tag, 2],
    "répugnance invincible et naturelle": [_xml_disagreement_tag, 7],
    "besoins absolument nécessaires": [_xml_dissatisfaction_tag, 5],
    "différence tellement profonde": [_xml_disagreement_tag, 5],
    "certain et inexprimable charme": [_xml_satisfaction_tag, 6],
    "ni des contradictions réelles": [_xml_agreement_tag, 8],
    "assurément la plus agréable": [_xml_satisfaction_tag, 7],
    "absolument aucune différence": [_xml_agreement_tag, 5],
    "guerre immense et nécessaire": [_xml_disagreement_tag, 6],
    "plus rigoureusement possible": [_xml_disagreement_tag, 3],
    "pas de conciliation possible": [_xml_disagreement_tag, 2],
    "différences considérables": [_xml_disagreement_tag, 4],
    "ne permet pas normalement": [_xml_disagreement_tag, 3],
    "satisfaites précisément": [_xml_satisfaction_tag, 5],
    "point du tout remarquable": [_xml_dissatisfaction_tag, 4],
    "contradictions apparentes": [_xml_disagreement_tag, 5],
    "différence plus sensible": [_xml_disagreement_tag, 5],
    "beaucoup moins importants": [_xml_satisfaction_tag, 2],
    "plus grande contrariété": [_xml_disagreement_tag, 6],
    "complètement incertaines": [_xml_dissatisfaction_tag, 6],
    "les plus simples possible": [_xml_satisfaction_tag, 5],
    "de plus en plus parfaites": [_xml_satisfaction_tag, 10],
    "point du tout agréables": [_xml_dissatisfaction_tag, 2],
    "le plus parfait du monde": [_xml_satisfaction_tag, 9],
    "n'autorise pas seulement": [_xml_disagreement_tag, 4],
    "grossièrement imaginée": [_xml_dissatisfaction_tag, 4],
    "vraiment extraordinaires": [_xml_satisfaction_tag, 9],
    "sans aucune satisfaction": [_xml_dissatisfaction_tag, 5],
    "plus ou moins importante": [_xml_satisfaction_tag, 4],
    "pas proprement brillante": [_xml_dissatisfaction_tag, 6],
    "aucunement la similitude": [_xml_disagreement_tag, 6],
    "tout à fait insuffisant": [_xml_dissatisfaction_tag, 7],
    "pas la seule différence": [_xml_agreement_tag, 1],
    "rapprochements possibles": [_xml_agreement_tag, 2],
    "plus ou moins plausibles": [_xml_agreement_tag, 3],
    "ne vous ai pas contredit": [_xml_agreement_tag, 3],
    "de plus en plus parfaits": [_xml_satisfaction_tag, 10],
    "sympathie bien naturelle": [_xml_agreement_tag, 6],
    "sans doute plus efficace": [_xml_satisfaction_tag, 8],
    "contradiction manifeste": [_xml_disagreement_tag, 5],
    "évidente contradiction": [_xml_disagreement_tag, 5],
    "apparente contradiction": [_xml_disagreement_tag, 5],
    "différence essentielle": [_xml_disagreement_tag, 5],
    "point le plus important": [_xml_dissatisfaction_tag, 9],
    "de plus en plus simples": [_xml_satisfaction_tag, 6],
    "rien de plus saisissant": [_xml_dissatisfaction_tag, 5],
    "pas moins intéressants": [_xml_dissatisfaction_tag, 2],
    "loin d'être aussi bien": [_xml_dissatisfaction_tag, 4],
    "passablement lamentable": [_xml_dissatisfaction_tag, 6],
    "prétendue conciliation": [_xml_agreement_tag, 2],
    "ne se contentât pas de": [_xml_dissatisfaction_tag, 3],
    "absolument insuffisants": [_xml_dissatisfaction_tag, 7],
    "virtuellement possibles": [_xml_agreement_tag, 3],
    "parfaitement ennuyeuses": [_xml_dissatisfaction_tag, 7],
    "singulier rapprochement": [_xml_agreement_tag, 5],
    "généralement adoptée": [_xml_agreement_tag, 5],
    "ne me désavouerait pas": [_xml_agreement_tag, 5],
    "Association remarquable": [_xml_agreement_tag, 5],
    "contradiction apparente": [_xml_disagreement_tag, 5],
    "nullement en désaccord": [_xml_agreement_tag, 6],
    "généralement douteuse": [_xml_disagreement_tag, 5],
    "horrible contradiction": [_xml_disagreement_tag, 6],
    "perfection plus grande": [_xml_satisfaction_tag, 8],
    "ne nous permettent pas": [_xml_disagreement_tag, 4],
    "ne vous est pas permis": [_xml_disagreement_tag, 4],
    "les plus merveilleuses": [_xml_satisfaction_tag, 8],
    "rapprochements curieux": [_xml_agreement_tag, 2],
    "plus ultra de la belle": [_xml_dissatisfaction_tag, 2],
    "essentiellement nulles": [_xml_dissatisfaction_tag, 6],
    "plus ou moins parfaite": [_xml_satisfaction_tag, 6],
    "simplement raisonnable": [_xml_agreement_tag, 3],
    "seulement insuffisante": [_xml_dissatisfaction_tag, 3],
    "ne manqueraient pas de": [_xml_satisfaction_tag, 3],
    "sans doute plus grande": [_xml_satisfaction_tag, 9],
    "de plus en plus grands": [_xml_satisfaction_tag, 9],
    "différences relatives": [_xml_disagreement_tag, 2],
    "parfaitement expliqué": [_xml_satisfaction_tag, 7],
    "autrement sans dommage": [_xml_satisfaction_tag, 5],
    "plus grande perfection": [_xml_satisfaction_tag, 8],
    "vraiment insuffisante": [_xml_dissatisfaction_tag, 7],
    "plus ou moins parfait": [_xml_satisfaction_tag, 6],
    "rien d'extraordinaire": [_xml_dissatisfaction_tag, 9],
    "opposition générale": [_xml_disagreement_tag, 5],
    "discussion générale": [_xml_disagreement_tag, 5],
    "ne vous manquerai pas": [_xml_satisfaction_tag, 3],
    "convenablement faites": [_xml_satisfaction_tag, 3],
    "attaquable uniquement": [_xml_disagreement_tag, 2],
    "passablement ennuyeux": [_xml_dissatisfaction_tag, 4],
    "plus grandes disputes": [_xml_disagreement_tag, 6],
    "contradiction cruelle": [_xml_disagreement_tag, 6],
    "division fondamentale": [_xml_disagreement_tag, 6],
    "beaucoup plus grandes": [_xml_satisfaction_tag, 9],
    "moindre contradiction": [_xml_disagreement_tag, 3],
    "prétendue opposition": [_xml_disagreement_tag, 3],
    "Bizarre contradiction": [_xml_disagreement_tag, 3],
    "discussions relatives": [_xml_disagreement_tag, 3],
    "les plus remarquables": [_xml_satisfaction_tag, 7],
    "plus ou moins grandes": [_xml_satisfaction_tag, 5],
    "pleinement satisfaits": [_xml_satisfaction_tag, 5],
    "uniquement élaborés": [_xml_satisfaction_tag, 3],
    "ne nous permet pas de": [_xml_disagreement_tag, 4],
    "ne nous permet pas d'": [_xml_disagreement_tag, 4],
    "ne me manquèrent pas": [_xml_satisfaction_tag, 3],
    "nullement attristante": [_xml_satisfaction_tag, 8],
    "inimitable perfection": [_xml_satisfaction_tag, 8],
    "traités particuliers": [_xml_agreement_tag, 5],
    "beaucoup moins grande": [_xml_satisfaction_tag, 3],
    "ne se contente pas de": [_xml_dissatisfaction_tag, 3],
    "plus vive approbation": [_xml_agreement_tag, 6],
    "beaucoup insuffisante": [_xml_dissatisfaction_tag, 7],
    "positivement réglée": [_xml_pleasure_tag, 7],
    "plus ou moins grande": [_xml_satisfaction_tag, 5],
    "ne reconnaissons pas": [_xml_disagreement_tag, 3],
    "très intéressantes": [_xml_satisfaction_tag, 4],
    "mauvaises sans doute": [_xml_dissatisfaction_tag, 6],
    "ne nous manquent pas": [_xml_satisfaction_tag, 3],
    "les plus éloignées": [_xml_disagreement_tag, 6],
    "ni plus intéressant": [_xml_dissatisfaction_tag, 2],
    "ne manquaient pas de": [_xml_satisfaction_tag, 3],
    "les plus merveilleux": [_xml_satisfaction_tag, 8],
    "grandes différences": [_xml_disagreement_tag, 4],
    "ne permettent pas d'": [_xml_disagreement_tag, 4],
    "perfections infinies": [_xml_satisfaction_tag, 8],
    "souveraine injustice": [_xml_dissatisfaction_tag, 7],
    "Ne me contentant pas": [_xml_dissatisfaction_tag, 3],
    "Rien de plus bizarre": [_xml_satisfaction_tag, 4],
    "ne conteste pas plus": [_xml_agreement_tag, 3],
    "extrêmement simples": [_xml_satisfaction_tag, 6],
    "remarquablement beau": [_xml_satisfaction_tag, 4],
    "raffinement ridicule": [_xml_satisfaction_tag, 4],
    "division incomplète": [_xml_disagreement_tag, 2],
    "les plus convenables": [_xml_satisfaction_tag, 5],
    "beaucoup plus grande": [_xml_satisfaction_tag, 9],
    "harmonies naturelles": [_xml_agreement_tag, 5],
    "les plus magnifiques": [_xml_satisfaction_tag, 7],
    "nul traité possible": [_xml_disagreement_tag, 5],
    "discussion sérieuse": [_xml_disagreement_tag, 5],
    "les plus autorisées": [_xml_agreement_tag, 6],
    "les plus compétents": [_xml_satisfaction_tag, 5],
    "le plus intéressant": [_xml_satisfaction_tag, 5],
    "énorme différence": [_xml_disagreement_tag, 5],
    "fortement disputée": [_xml_disagreement_tag, 5],
    "tellement grossiers": [_xml_dissatisfaction_tag, 5],
    "tellement savoureux": [_xml_satisfaction_tag, 6],
    "très satisfaisante": [_xml_satisfaction_tag, 6],
    "perfection possible": [_xml_satisfaction_tag, 5],
    "ne manque guère de": [_xml_satisfaction_tag, 2],
    "perfection suprême": [_xml_satisfaction_tag, 8],
    "presque effrayantes": [_xml_dissatisfaction_tag, 6],
    "pas moins de bonnes": [_xml_dissatisfaction_tag, 2],
    "les plus éloignés": [_xml_disagreement_tag, 6],
    "rien de plus simple": [_xml_dissatisfaction_tag, 2],
    "certaine perfection": [_xml_satisfaction_tag, 8],
    "tout exceptionnelle": [_xml_satisfaction_tag, 8],
    "aucunement plus mal": [_xml_satisfaction_tag, 4],
    "ne permettaient pas": [_xml_disagreement_tag, 4],
    "grande satisfaction": [_xml_satisfaction_tag, 4],
    "infiniment pénible": [_xml_dissatisfaction_tag, 7],
    "farouche stupidité": [_xml_dissatisfaction_tag, 7],
    "point de perfection": [_xml_dissatisfaction_tag, 8],
    "les plus importants": [_xml_satisfaction_tag, 7],
    "pas de différences": [_xml_agreement_tag, 3],
    "le plus remarquable": [_xml_satisfaction_tag, 7],
    "les plus honorables": [_xml_satisfaction_tag, 5],
    "plus ou moins grand": [_xml_satisfaction_tag, 5],
    "nul pour ainsi dire": [_xml_dissatisfaction_tag, 4],
    "vraiment incroyable": [_xml_satisfaction_tag, 9],
    "les plus charmantes": [_xml_satisfaction_tag, 6],
    "remarquable surtout": [_xml_satisfaction_tag, 6],
    "harmonie générale": [_xml_agreement_tag, 5],
    "consensus général": [_xml_agreement_tag, 5],
    "pratiquement permis": [_xml_agreement_tag, 5],
    "beaucoup de besoins": [_xml_dissatisfaction_tag, 5],
    "conflit nécessaire": [_xml_disagreement_tag, 5],
    "autant de divisions": [_xml_disagreement_tag, 5],
    "désaccord sensible": [_xml_disagreement_tag, 5],
    "harmonie étonnante": [_xml_agreement_tag, 6],
    "parfaitement permis": [_xml_agreement_tag, 6],
    "aucune contestation": [_xml_agreement_tag, 6],
    "ni en contradiction": [_xml_agreement_tag, 6],
    "point les querelles": [_xml_agreement_tag, 7],
    "contraste essentiel": [_xml_disagreement_tag, 5],
    "graves différences": [_xml_disagreement_tag, 5],
    "pas de le soutenir": [_xml_disagreement_tag, 4],
    "divisions absolues": [_xml_disagreement_tag, 6],
    "plus de divergence": [_xml_disagreement_tag, 6],
    "rude contradiction": [_xml_disagreement_tag, 6],
    "contradiction pure": [_xml_disagreement_tag, 6],
    "grande différence": [_xml_disagreement_tag, 4],
    "ne nous permet pas": [_xml_disagreement_tag, 4],
    "la plus convenable": [_xml_satisfaction_tag, 5],
    "point d'une grande": [_xml_dissatisfaction_tag, 8],
    "laid foncièrement": [_xml_dissatisfaction_tag, 8],
    "charme particulier": [_xml_satisfaction_tag, 5],
    "éminemment belles": [_xml_satisfaction_tag, 5],
    "peu de différence": [_xml_disagreement_tag, 1],
    "relativement bonne": [_xml_satisfaction_tag, 2],
    "la plus importante": [_xml_satisfaction_tag, 7],
    "pas moins le grand": [_xml_dissatisfaction_tag, 5],
    "ne refusent pas d'": [_xml_agreement_tag, 4],
    "sans contradiction": [_xml_agreement_tag, 4],
    "admis en général": [_xml_agreement_tag, 4],
    "ne discuterons pas": [_xml_agreement_tag, 4],
    "ne refusera pas de": [_xml_agreement_tag, 4],
    "plus de perfection": [_xml_satisfaction_tag, 8],
    "perfection idéale": [_xml_satisfaction_tag, 8],
    "absolue perfection": [_xml_satisfaction_tag, 8],
    "plus merveilleuses": [_xml_satisfaction_tag, 8],
    "les plus originaux": [_xml_satisfaction_tag, 8],
    "plus satisfaisante": [_xml_satisfaction_tag, 7],
    "profonde injustice": [_xml_dissatisfaction_tag, 6],
    "pas si fantastique": [_xml_dissatisfaction_tag, 6],
    "sans rapprochement": [_xml_disagreement_tag, 3],
    "n'admettons pas de": [_xml_disagreement_tag, 3],
    "unité nécessaire": [_xml_agreement_tag, 5],
    "convenu entre nous": [_xml_agreement_tag, 5],
    "équilibre parfait": [_xml_agreement_tag, 5],
    "aucune différence": [_xml_agreement_tag, 5],
    "bien insuffisantes": [_xml_dissatisfaction_tag, 6],
    "n'admettons aucune": [_xml_disagreement_tag, 5],
    "division naturelle": [_xml_disagreement_tag, 5],
    "suffisamment bonne": [_xml_satisfaction_tag, 2],
    "vraiment plaisants": [_xml_satisfaction_tag, 6],
    "très bien produit": [_xml_satisfaction_tag, 6],
    "très remarquables": [_xml_satisfaction_tag, 6],
    "le plus convenable": [_xml_satisfaction_tag, 5],
    "ne refuse point de": [_xml_agreement_tag, 6],
    "absolument simples": [_xml_satisfaction_tag, 5],
    "aucune répugnance": [_xml_agreement_tag, 7],
    "infiniment parfait": [_xml_satisfaction_tag, 9],
    "besoin particulier": [_xml_dissatisfaction_tag, 4],
    "pas fort contente": [_xml_dissatisfaction_tag, 2],
    "Rien de plus beau": [_xml_dissatisfaction_tag, 2],
    "trop sophistiqué": [_xml_satisfaction_tag, 8],
    "sûrement simples": [_xml_satisfaction_tag, 5],
    "très insuffisant": [_xml_dissatisfaction_tag, 6],
    "fort intéressant": [_xml_satisfaction_tag, 4],
    "moins saisissants": [_xml_satisfaction_tag, 4],
    "pas plus possible": [_xml_disagreement_tag, 3],
    "ne reconnaît pas": [_xml_disagreement_tag, 3],
    "aucune contrainte": [_xml_satisfaction_tag, 5],
    "ne se lassait pas": [_xml_satisfaction_tag, 5],
    "aucunement besoin": [_xml_satisfaction_tag, 5],
    "la plus charmante": [_xml_satisfaction_tag, 6],
    "très merveilleux": [_xml_satisfaction_tag, 7],
    "vraiment parfaits": [_xml_satisfaction_tag, 9],
    "absolument nulles": [_xml_dissatisfaction_tag, 7],
    "la plus brillante": [_xml_satisfaction_tag, 9],
    "Rien de médiocre": [_xml_satisfaction_tag, 7],
    "grande perfection": [_xml_satisfaction_tag, 7],
    "les plus sublimes": [_xml_satisfaction_tag, 10],
    "le plus important": [_xml_satisfaction_tag, 7],
    "ne permettent pas": [_xml_disagreement_tag, 4],
    "union nécessaire": [_xml_agreement_tag, 5],
    "autre différence": [_xml_disagreement_tag, 4],
    "n'eût pas permis": [_xml_disagreement_tag, 4],
    "ne permettait pas": [_xml_disagreement_tag, 4],
    "ni la plus grande": [_xml_dissatisfaction_tag, 10],
    "aussi singulière": [_xml_satisfaction_tag, 7],
    "seule différence": [_xml_disagreement_tag, 1],
    "besoin insatiable": [_xml_dissatisfaction_tag, 5],
    "très importantes": [_xml_satisfaction_tag, 6],
    "terriblement beau": [_xml_satisfaction_tag, 5],
    "harmonie parfaite": [_xml_agreement_tag, 6],
    "lui-même soutenu": [_xml_agreement_tag, 6],
    "farouche alliance": [_xml_agreement_tag, 6],
    "parfaite harmonie": [_xml_agreement_tag, 6],
    "le moins possible": [_xml_agreement_tag, 2],
    "la plus splendide": [_xml_satisfaction_tag, 8],
    "excellent traité": [_xml_agreement_tag, 7],
    "plus merveilleuse": [_xml_satisfaction_tag, 8],
    "infiniment grands": [_xml_satisfaction_tag, 8],
    "les plus mauvais": [_xml_dissatisfaction_tag, 7],
    "pas parfaitement": [_xml_dissatisfaction_tag, 7],
    "les plus simples": [_xml_satisfaction_tag, 5],
    "n'est pas permis": [_xml_disagreement_tag, 4],
    "ne permet pas de": [_xml_disagreement_tag, 4],
    "pas insuffisante": [_xml_satisfaction_tag, 5],
    "pas tant de bien": [_xml_dissatisfaction_tag, 4],
    "rien d'étonnant": [_xml_dissatisfaction_tag, 8],
    "pas bien refuser": [_xml_agreement_tag, 3],
    "ni la perfection": [_xml_dissatisfaction_tag, 8],
    "pas tout le bien": [_xml_dissatisfaction_tag, 4],
    "tout à fait bon": [_xml_satisfaction_tag, 5],
    "les plus affreux": [_xml_dissatisfaction_tag, 9],
    "pas de mauvaises": [_xml_satisfaction_tag, 5],
    "pas la repousser": [_xml_agreement_tag, 4],
    "autre équilibre": [_xml_agreement_tag, 4],
    "la plus parfaite": [_xml_satisfaction_tag, 9],
    "la plus honnête": [_xml_satisfaction_tag, 5],
    "aussi honorables": [_xml_satisfaction_tag, 4],
    "assez importante": [_xml_satisfaction_tag, 4],
    "moins de besoins": [_xml_dissatisfaction_tag, 1],
    "très incertaine": [_xml_dissatisfaction_tag, 5],
    "fort incertaines": [_xml_dissatisfaction_tag, 5],
    "pas aussi grands": [_xml_dissatisfaction_tag, 5],
    "ne manque pas de": [_xml_satisfaction_tag, 3],
    "si intéressants": [_xml_satisfaction_tag, 4],
    "plus sympathique": [_xml_satisfaction_tag, 6],
    "bien remarquable": [_xml_satisfaction_tag, 6],
    "Le plus charmant": [_xml_satisfaction_tag, 6],
    "plus remarquable": [_xml_satisfaction_tag, 7],
    "contraste hideux": [_xml_disagreement_tag, 5],
    "bien raisonnable": [_xml_agreement_tag, 5],
    "sans répugnance": [_xml_agreement_tag, 5],
    "symétrie double": [_xml_agreement_tag, 5],
    "plus importantes": [_xml_satisfaction_tag, 7],
    "le plus original": [_xml_satisfaction_tag, 8],
    "les plus grandes": [_xml_satisfaction_tag, 8],
    "pas reconnaître": [_xml_disagreement_tag, 3],
    "plus saisissante": [_xml_satisfaction_tag, 8],
    "plus grossières": [_xml_dissatisfaction_tag, 6],
    "infiniment grand": [_xml_satisfaction_tag, 8],
    "fort remarquable": [_xml_satisfaction_tag, 6],
    "très importants": [_xml_satisfaction_tag, 6],
    "le moins mauvais": [_xml_dissatisfaction_tag, 3],
    "assez mécontent": [_xml_dissatisfaction_tag, 3],
    "aussi importante": [_xml_satisfaction_tag, 6],
    "très importante": [_xml_satisfaction_tag, 6],
    "le plus possible": [_xml_agreement_tag, 6],
    "singulier accord": [_xml_agreement_tag, 6],
    "division cruelle": [_xml_disagreement_tag, 6],
    "plein de charmes": [_xml_satisfaction_tag, 6],
    "plus convenables": [_xml_satisfaction_tag, 5],
    "la plus mauvaise": [_xml_dissatisfaction_tag, 7],
    "la plus pénible": [_xml_dissatisfaction_tag, 7],
    "le moins permis": [_xml_agreement_tag, 2],
    "plus admirables": [_xml_satisfaction_tag, 7],
    "pas soutenables": [_xml_disagreement_tag, 4],
    "très étonnant": [_xml_satisfaction_tag, 7],
    "ne manquait pas": [_xml_satisfaction_tag, 3],
    "simples environ": [_xml_satisfaction_tag, 2],
    "aussi important": [_xml_satisfaction_tag, 6],
    "plus charmantes": [_xml_satisfaction_tag, 6],
    "plus séduisant": [_xml_satisfaction_tag, 6],
    "aussi admirable": [_xml_satisfaction_tag, 6],
    "très important": [_xml_satisfaction_tag, 6],
    "le plus parfait": [_xml_satisfaction_tag, 9],
    "bien plus grand": [_xml_satisfaction_tag, 9],
    "assez agréable": [_xml_satisfaction_tag, 2],
    "peu sympathique": [_xml_satisfaction_tag, 2],
    "sans un trouble": [_xml_agreement_tag, 4],
    "pas désavoués": [_xml_agreement_tag, 4],
    "ne conteste pas": [_xml_agreement_tag, 4],
    "si grand besoin": [_xml_dissatisfaction_tag, 5],
    "pas assez grand": [_xml_dissatisfaction_tag, 5],
    "pas plus grande": [_xml_dissatisfaction_tag, 5],
    "moins satisfait": [_xml_satisfaction_tag, 1],
    "le plus sublime": [_xml_satisfaction_tag, 10],
    "ne manquais pas": [_xml_satisfaction_tag, 3],
    "moins de besoin": [_xml_dissatisfaction_tag, 1],
    "moins ambitieux": [_xml_satisfaction_tag, 4],
    "si sympathiques": [_xml_satisfaction_tag, 5],
    "bien expliquée": [_xml_satisfaction_tag, 5],
    "grande division": [_xml_disagreement_tag, 5],
    "division simple": [_xml_disagreement_tag, 5],
    "bien éloignés": [_xml_disagreement_tag, 5],
    "bien éloignée": [_xml_disagreement_tag, 5],
    "fort éloignée": [_xml_disagreement_tag, 5],
    "bien travaillé": [_xml_satisfaction_tag, 5],
    "plus convenable": [_xml_satisfaction_tag, 5],
    "grande harmonie": [_xml_agreement_tag, 5],
    "les plus belles": [_xml_satisfaction_tag, 5],
    "très mauvaises": [_xml_dissatisfaction_tag, 6],
    "bien médiocres": [_xml_dissatisfaction_tag, 6],
    "plus incertaine": [_xml_dissatisfaction_tag, 6],
    "sans grandement": [_xml_dissatisfaction_tag, 6],
    "plus agréables": [_xml_satisfaction_tag, 5],
    "très honorable": [_xml_satisfaction_tag, 4],
    "pas tout le mal": [_xml_satisfaction_tag, 4],
    "ne manquent pas": [_xml_satisfaction_tag, 3],
    "plus importants": [_xml_satisfaction_tag, 7],
    "si merveilleuse": [_xml_satisfaction_tag, 7],
    "les plus grands": [_xml_satisfaction_tag, 8],
    "plus discutable": [_xml_disagreement_tag, 6],
    "Guerre terrible": [_xml_disagreement_tag, 6],
    "aussi brillants": [_xml_satisfaction_tag, 8],
    "point la guerre": [_xml_agreement_tag, 6],
    "point éloigné": [_xml_agreement_tag, 6],
    "harmonie totale": [_xml_agreement_tag, 6],
    "le plus énorme": [_xml_satisfaction_tag, 8],
    "vraiment grands": [_xml_satisfaction_tag, 8],
    "si monstrueuses": [_xml_satisfaction_tag, 8],
    "plus importante": [_xml_satisfaction_tag, 7],
    "tant excellente": [_xml_satisfaction_tag, 7],
    "tant excellent": [_xml_satisfaction_tag, 7],
    "fort étonnant": [_xml_satisfaction_tag, 7],
    "peu de besoins": [_xml_dissatisfaction_tag, 1],
    "peu convenable": [_xml_satisfaction_tag, 1],
    "pas en manquer": [_xml_satisfaction_tag, 3],
    "sans contredit": [_xml_agreement_tag, 3],
    "plus pitoyable": [_xml_dissatisfaction_tag, 8],
    "point original": [_xml_dissatisfaction_tag, 8],
    "fort agréable": [_xml_satisfaction_tag, 4],
    "bien satisfait": [_xml_satisfaction_tag, 4],
    "les plus beaux": [_xml_satisfaction_tag, 5],
    "aussi parfaite": [_xml_satisfaction_tag, 8],
    "plus de besoin": [_xml_dissatisfaction_tag, 5],
    "point contents": [_xml_dissatisfaction_tag, 5],
    "immense besoin": [_xml_dissatisfaction_tag, 5],
    "plus singulier": [_xml_satisfaction_tag, 8],
    "pas discutable": [_xml_agreement_tag, 4],
    "pas désavoué": [_xml_agreement_tag, 4],
    "la plus grande": [_xml_satisfaction_tag, 8],
    "le plus simple": [_xml_satisfaction_tag, 5],
    "plus aussi bon": [_xml_dissatisfaction_tag, 2],
    "assez coûteux": [_xml_dissatisfaction_tag, 2],
    "bien préparé": [_xml_satisfaction_tag, 5],
    "la plus simple": [_xml_satisfaction_tag, 5],
    "bien expliqué": [_xml_satisfaction_tag, 5],
    "bien organisé": [_xml_satisfaction_tag, 5],
    "très efficace": [_xml_satisfaction_tag, 6],
    "pas les bonnes": [_xml_dissatisfaction_tag, 3],
    "assez parfaite": [_xml_satisfaction_tag, 6],
    "plus de charme": [_xml_satisfaction_tag, 6],
    "bien éloigné": [_xml_disagreement_tag, 5],
    "plus charmants": [_xml_satisfaction_tag, 6],
    "pas admissible": [_xml_disagreement_tag, 3],
    "pas une grande": [_xml_dissatisfaction_tag, 6],
    "très pénible": [_xml_dissatisfaction_tag, 6],
    "plus grossiers": [_xml_dissatisfaction_tag, 6],
    "tant possibles": [_xml_agreement_tag, 5],
    "simple amitié": [_xml_agreement_tag, 5],
    "Profond accord": [_xml_agreement_tag, 5],
    "très permises": [_xml_agreement_tag, 5],
    "haute harmonie": [_xml_agreement_tag, 5],
    "pas d'énormes": [_xml_dissatisfaction_tag, 6],
    "pas les grands": [_xml_dissatisfaction_tag, 6],
    "bien plaisante": [_xml_satisfaction_tag, 5],
    "fort satisfait": [_xml_satisfaction_tag, 4],
    "peu agréables": [_xml_satisfaction_tag, 1],
    "plus brillante": [_xml_satisfaction_tag, 9],
    "plus brillants": [_xml_satisfaction_tag, 9],
    "guère réussi": [_xml_dissatisfaction_tag, 4],
    "privé de tout": [_xml_dissatisfaction_tag, 4],
    "assez bizarres": [_xml_dissatisfaction_tag, 4],
    "pas moins bien": [_xml_dissatisfaction_tag, 4],
    "trop éloigné": [_xml_disagreement_tag, 6],
    "point d'accord": [_xml_disagreement_tag, 6],
    "si merveilleux": [_xml_satisfaction_tag, 7],
    "excellentes si": [_xml_satisfaction_tag, 7],
    "plus important": [_xml_satisfaction_tag, 7],
    "plus admirable": [_xml_satisfaction_tag, 7],
    "plus mauvaises": [_xml_dissatisfaction_tag, 7],
    "accord parfait": [_xml_agreement_tag, 6],
    "point disputer": [_xml_agreement_tag, 6],
    "pas les signes": [_xml_disagreement_tag, 4],
    "n'approuve pas": [_xml_disagreement_tag, 4],
    "seule alliance": [_xml_agreement_tag, 2],
    "pas soutenable": [_xml_disagreement_tag, 4],
    "pas une unité": [_xml_disagreement_tag, 4],
    "ne nie pas d'": [_xml_agreement_tag, 4],
    "reconnus tout": [_xml_agreement_tag, 4],
    "si élégante": [_xml_satisfaction_tag, 6],
    "bien soignés": [_xml_satisfaction_tag, 6],
    "plus correcte": [_xml_satisfaction_tag, 5],
    "trop honnête": [_xml_satisfaction_tag, 5],
    "plus stupides": [_xml_dissatisfaction_tag, 7],
    "aussi mignons": [_xml_satisfaction_tag, 5],
    "aussi simples": [_xml_satisfaction_tag, 4],
    "peu important": [_xml_satisfaction_tag, 3],
    "pas satisfait": [_xml_dissatisfaction_tag, 3],
    "pas de belles": [_xml_dissatisfaction_tag, 3],
    "pas un simple": [_xml_dissatisfaction_tag, 3],
    "pas le besoin": [_xml_satisfaction_tag, 3],
    "plus rebutant": [_xml_dissatisfaction_tag, 8],
    "rien de grand": [_xml_dissatisfaction_tag, 8],
    "tout haletant": [_xml_satisfaction_tag, 7],
    "très grandes": [_xml_satisfaction_tag, 7],
    "plus parfaits": [_xml_satisfaction_tag, 9],
    "ne permet pas": [_xml_disagreement_tag, 4],
    "n'accepte pas": [_xml_disagreement_tag, 4],
    "pas permettre": [_xml_disagreement_tag, 4],
    "ne permit pas": [_xml_disagreement_tag, 4],
    "plus parfaite": [_xml_satisfaction_tag, 9],
    "point injuste": [_xml_satisfaction_tag, 7],
    "seuls charmes": [_xml_satisfaction_tag, 2],
    "grande unité": [_xml_agreement_tag, 5],
    "peu agréable": [_xml_satisfaction_tag, 1],
    "ne manque pas": [_xml_satisfaction_tag, 3],
    "plus sublimes": [_xml_satisfaction_tag, 10],
    "tout honnête": [_xml_satisfaction_tag, 4],
    "très simples": [_xml_satisfaction_tag, 4],
    "si convenable": [_xml_satisfaction_tag, 4],
    "bien contents": [_xml_satisfaction_tag, 4],
    "pas de grands": [_xml_dissatisfaction_tag, 6],
    "fort pénible": [_xml_dissatisfaction_tag, 6],
    "pas étonnant": [_xml_dissatisfaction_tag, 6],
    "très mauvais": [_xml_dissatisfaction_tag, 6],
    "sans grandeur": [_xml_dissatisfaction_tag, 6],
    "aussi stupide": [_xml_dissatisfaction_tag, 6],
    "moins grandes": [_xml_satisfaction_tag, 4],
    "le plus grand": [_xml_satisfaction_tag, 8],
    "sans admettre": [_xml_disagreement_tag, 3],
    "si brillantes": [_xml_satisfaction_tag, 8],
    "plus honnête": [_xml_satisfaction_tag, 5],
    "plus possible": [_xml_agreement_tag, 6],
    "accordé trop": [_xml_agreement_tag, 6],
    "bonne amitié": [_xml_agreement_tag, 6],
    "la plus belle": [_xml_satisfaction_tag, 5],
    "la plus jolie": [_xml_satisfaction_tag, 5],
    "si importants": [_xml_satisfaction_tag, 6],
    "si importante": [_xml_satisfaction_tag, 6],
    "reconnue tout": [_xml_agreement_tag, 4],
    "n'admets pas": [_xml_disagreement_tag, 3],
    "très grands": [_xml_satisfaction_tag, 7],
    "très grande": [_xml_satisfaction_tag, 7],
    "assez simple": [_xml_satisfaction_tag, 2],
    "sans dommage": [_xml_satisfaction_tag, 3],
    "sans manquer": [_xml_satisfaction_tag, 3],
    "bien simples": [_xml_satisfaction_tag, 4],
    "très simple": [_xml_satisfaction_tag, 4],
    "moins permis": [_xml_agreement_tag, 2],
    "si attachant": [_xml_satisfaction_tag, 4],
    "si honorable": [_xml_satisfaction_tag, 4],
    "grand besoin": [_xml_dissatisfaction_tag, 4],
    "tout simples": [_xml_satisfaction_tag, 4],
    "plus grandes": [_xml_satisfaction_tag, 8],
    "si brillante": [_xml_satisfaction_tag, 8],
    "bien content": [_xml_satisfaction_tag, 4],
    "pas de refus": [_xml_agreement_tag, 5],
    "n'exclut pas": [_xml_agreement_tag, 5],
    "aussi simple": [_xml_satisfaction_tag, 4],
    "fort simples": [_xml_satisfaction_tag, 4],
    "moins simple": [_xml_satisfaction_tag, 1],
    "point manque": [_xml_satisfaction_tag, 5],
    "bien réglé": [_xml_satisfaction_tag, 5],
    "assez grande": [_xml_satisfaction_tag, 5],
    "bien mauvais": [_xml_dissatisfaction_tag, 6],
    "pas un grand": [_xml_dissatisfaction_tag, 6],
    "classe aussi": [_xml_satisfaction_tag, 6],
    "si élégant": [_xml_satisfaction_tag, 6],
    "si enchanté": [_xml_satisfaction_tag, 6],
    "si important": [_xml_satisfaction_tag, 6],
    "si admirable": [_xml_satisfaction_tag, 6],
    "pas possible": [_xml_disagreement_tag, 4],
    "pas accordé": [_xml_disagreement_tag, 4],
    "pas d'accord": [_xml_disagreement_tag, 4],
    "pas disputer": [_xml_agreement_tag, 4],
    "sans trouble": [_xml_agreement_tag, 4],
    "bien reconnu": [_xml_agreement_tag, 4],
    "pas si grand": [_xml_dissatisfaction_tag, 5],
    "plus simples": [_xml_satisfaction_tag, 5],
    "le plus beau": [_xml_satisfaction_tag, 5],
    "trop simples": [_xml_satisfaction_tag, 5],
    "point besoin": [_xml_satisfaction_tag, 5],
    "plus parfait": [_xml_satisfaction_tag, 9],
    "superbe tout": [_xml_satisfaction_tag, 7],
    "aucun accord": [_xml_disagreement_tag, 6],
    "trop simple": [_xml_satisfaction_tag, 5],
    "n'admet pas": [_xml_disagreement_tag, 3],
    "pas simples": [_xml_dissatisfaction_tag, 3],
    "plus jolies": [_xml_satisfaction_tag, 5],
    "assez grand": [_xml_satisfaction_tag, 5],
    "plus divine": [_xml_satisfaction_tag, 9],
    "le plus bel": [_xml_satisfaction_tag, 5],
    "si efficace": [_xml_satisfaction_tag, 6],
    "plus mignon": [_xml_satisfaction_tag, 6],
    "moins beaux": [_xml_satisfaction_tag, 1],
    "si contents": [_xml_satisfaction_tag, 4],
    "fort belles": [_xml_satisfaction_tag, 4],
    "plus grande": [_xml_satisfaction_tag, 8],
    "Trop grande": [_xml_satisfaction_tag, 8],
    "plus grands": [_xml_satisfaction_tag, 8],
    "trop grande": [_xml_satisfaction_tag, 8],
    "ni grandeur": [_xml_dissatisfaction_tag, 8],
    "plus fameux": [_xml_satisfaction_tag, 8],
    "si parfaite": [_xml_satisfaction_tag, 8],
    "si brillant": [_xml_satisfaction_tag, 8],
    "tout simple": [_xml_satisfaction_tag, 4],
    "fort simple": [_xml_satisfaction_tag, 4],
    "tout belles": [_xml_satisfaction_tag, 4],
    "bien simple": [_xml_satisfaction_tag, 4],
    "aussi belle": [_xml_satisfaction_tag, 4],
    "très bonne": [_xml_satisfaction_tag, 4],
    "pas manqué": [_xml_satisfaction_tag, 3],
    "assez bonne": [_xml_satisfaction_tag, 2],
    "très grand": [_xml_satisfaction_tag, 7],
    "si mauvaise": [_xml_dissatisfaction_tag, 6],
    "si stupides": [_xml_dissatisfaction_tag, 6],
    "sans grande": [_xml_dissatisfaction_tag, 6],
    "aussi grand": [_xml_satisfaction_tag, 7],
    "pas de nier": [_xml_agreement_tag, 4],
    "pas douteux": [_xml_agreement_tag, 4],
    "plus belles": [_xml_satisfaction_tag, 5],
    "pas mauvais": [_xml_satisfaction_tag, 5],
    "trop belles": [_xml_satisfaction_tag, 5],
    "plus simple": [_xml_satisfaction_tag, 5],
    "pas de bien": [_xml_dissatisfaction_tag, 5],
    "plus permis": [_xml_agreement_tag, 6],
    "pas réussi": [_xml_dissatisfaction_tag, 5],
    "point signe": [_xml_disagreement_tag, 6],
    "aucun signe": [_xml_disagreement_tag, 6],
    "pas un bien": [_xml_dissatisfaction_tag, 5],
    "bien faites": [_xml_satisfaction_tag, 5],
    "aussi beau": [_xml_satisfaction_tag, 4],
    "bien jolie": [_xml_satisfaction_tag, 4],
    "tout beaux": [_xml_satisfaction_tag, 4],
    "pas besoin": [_xml_satisfaction_tag, 3],
    "grand tout": [_xml_satisfaction_tag, 7],
    "si grandes": [_xml_satisfaction_tag, 7],
    "pas de bon": [_xml_dissatisfaction_tag, 3],
    "pas un bon": [_xml_dissatisfaction_tag, 3],
    "fort grand": [_xml_satisfaction_tag, 7],
    "ne nie pas": [_xml_agreement_tag, 4],
    "bien grand": [_xml_satisfaction_tag, 7],
    "tant bonne": [_xml_satisfaction_tag, 4],
    "plus laids": [_xml_dissatisfaction_tag, 7],
    "sans nulle": [_xml_satisfaction_tag, 5],
    "nul besoin": [_xml_satisfaction_tag, 5],
    "plus beaux": [_xml_satisfaction_tag, 5],
    "plus belle": [_xml_satisfaction_tag, 5],
    "pas de mal": [_xml_satisfaction_tag, 5],
    "pas permis": [_xml_disagreement_tag, 4],
    "bien finie": [_xml_satisfaction_tag, 5],
    "pur besoin": [_xml_dissatisfaction_tag, 5],
    "mal faites": [_xml_dissatisfaction_tag, 5],
    "fort belle": [_xml_satisfaction_tag, 4],
    "si simples": [_xml_satisfaction_tag, 4],
    "si affreux": [_xml_dissatisfaction_tag, 8],
    "plus grand": [_xml_satisfaction_tag, 8],
    "plus divin": [_xml_satisfaction_tag, 9],
    "bien nulle": [_xml_dissatisfaction_tag, 6],
    "sans grand": [_xml_dissatisfaction_tag, 6],
    "pas abouti": [_xml_dissatisfaction_tag, 4],
    "si sublime": [_xml_satisfaction_tag, 9],
    "trop grand": [_xml_satisfaction_tag, 8],
    "fort bonne": [_xml_satisfaction_tag, 4],
    "bien fait": [_xml_satisfaction_tag, 5],
    "si atroce": [_xml_dissatisfaction_tag, 8],
    "ni grands": [_xml_dissatisfaction_tag, 8],
    "plus joli": [_xml_satisfaction_tag, 5],
    "bien beau": [_xml_satisfaction_tag, 4],
    "Tout beau": [_xml_satisfaction_tag, 4],
    "beau tout": [_xml_satisfaction_tag, 4],
    "si bonnes": [_xml_satisfaction_tag, 4],
    "assez bon": [_xml_satisfaction_tag, 2],
    "si belles": [_xml_satisfaction_tag, 4],
    "ni classe": [_xml_dissatisfaction_tag, 7],
    "plus laid": [_xml_dissatisfaction_tag, 7],
    "fort laid": [_xml_dissatisfaction_tag, 6],
    "pas grand": [_xml_dissatisfaction_tag, 6],
    "tant beau": [_xml_satisfaction_tag, 4],
    "si souple": [_xml_agreement_tag, 4],
    "tout beau": [_xml_satisfaction_tag, 4],
    "fort bons": [_xml_satisfaction_tag, 4],
    "si simple": [_xml_satisfaction_tag, 4],
    "fort beau": [_xml_satisfaction_tag, 4],
    "si grande": [_xml_satisfaction_tag, 7],
    "point mal": [_xml_satisfaction_tag, 7],
    "plus beau": [_xml_satisfaction_tag, 5],
    "dur refus": [_xml_disagreement_tag, 6],
    "Tout bon": [_xml_satisfaction_tag, 4],
    "tout bon": [_xml_satisfaction_tag, 4],
    "bien bon": [_xml_satisfaction_tag, 4],
    "si bonne": [_xml_satisfaction_tag, 4],
    "mal fait": [_xml_dissatisfaction_tag, 5],
    "pas bien": [_xml_dissatisfaction_tag, 5],
    "plus bel": [_xml_satisfaction_tag, 5],
    "nul plus": [_xml_dissatisfaction_tag, 7],
    "sans nul": [_xml_satisfaction_tag, 5],
    "sans mal": [_xml_satisfaction_tag, 5],
    "si belle": [_xml_satisfaction_tag, 4],
    "fort bon": [_xml_satisfaction_tag, 4],
    "si beaux": [_xml_satisfaction_tag, 4],
    "si grand": [_xml_satisfaction_tag, 7],
    "pas mal": [_xml_satisfaction_tag, 5],
    "pas bon": [_xml_dissatisfaction_tag, 3],
    "si fade": [_xml_dissatisfaction_tag, 3],
    "ni bien": [_xml_dissatisfaction_tag, 7],
    "si beau": [_xml_satisfaction_tag, 4],
    "si nul": [_xml_dissatisfaction_tag, 6],
    "si bon": [_xml_satisfaction_tag, 4],
    "si bel": [_xml_satisfaction_tag, 4],   
}